from src.env.echo_env import DEFAULT_MAX_STEPS

N_TRAIN_SAMPLES = 5_000
N_VAL_SAMPLES = 50
BATCH_SIZE = 16
EPOCHS = 20
LEARNING_RATE = 1e-3
STEPS_PER_SAMPLE = DEFAULT_MAX_STEPS
CACHE_STEPS_PER_SAMPLE = 60  # maps saturate early; much faster cache generation
MAX_OBJECTS = 8
MAX_PEOPLE = 4
DATALOADER_WORKERS = 0
DEFAULT_GEN_WORKERS = 2

DEFAULT_RL_CHECKPOINT = "checkpoints/echo_100000_steps.zip"
CACHE_DIR = "data/cnn_cache"
CHECKPOINT_DIR = "checkpoints/cnn"
BEST_MODEL_PATH = f"{CHECKPOINT_DIR}/best_model.pt"
LATEST_MODEL_PATH = f"{CHECKPOINT_DIR}/latest_model.pt"
